name: CI/CD DEMO PIPELINE WITH SUMO LOGIC

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run tests
              run: npm test

            - name: Send logs to Sumo Logic
              run: |
                curl -X POST -H "Content-Type: text/plain" -d "@path/to/log/file.log" "https://collectors.jp.sumologic.com/receiver/v1/http/ZaVnC4dhaV2L67Xe22tX7QttCmKqOwnJ8LrOWw5t065FIRfZWU2WjAP_TLyAw7rQEJOBn3zFhy0QpND9CbFxD3oyjaF7ZsxMH_VZm0jIXH_J2laxUCvjMQ=="
                echo "Sending logs to Sumo Logic"
